# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  valgrind_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare environment
        run: sudo apt update && sudo apt install build-essential libgtest-dev cmake gcc valgrind
      - name: build
        run: cmake . -Bbuild && cmake --build build --target tests
      - name: valgrind_memcheck
        run: valgrind --tool=memcheck --leak-check=yes --error-exitcode=1 ./build/test/tests
  sanitaizer_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare environment
        run: sudo apt update && sudo apt install build-essential libgtest-dev cmake gcc valgrind
      - name: build
        run: cmake . -Bbuild -DBUILD_SANITIZERS=1 && cmake --build build --target tests
      - name: sanitizer_memcheck
        run: ./build/test/tests
  sanitaizer_thread_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare environment
        run: sudo apt update && sudo apt install build-essential libgtest-dev cmake gcc valgrind
      - name: build
        run: cmake . -Bbuild -DBUILD_SANITIZERS_THREAD=1 && cmake --build build --target tests
      - name: thread_sanitizer_check
        run: ./build/tests/tests
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare environment
        run: sudo apt update && sudo apt install python3 python3-pip && pip3 install --user cpplint
      - name: lint
        run: ~/.local/bin/cpplint --recursive .
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare environment
        run: sudo apt update && sudo apt install build-essential cmake gcc lcov libgtest-dev
      - name: build
        run: cmake . -Bbuild && cmake --build build --target tests
      - name: test run
        run: ./build/tests/tests
      - name: codecov
        run: lcov -t "./build/tests/tests" -o coverage.info -c -d "./build/matrix_tranposition_lib/CMakeFiles/m_transpose_lib.dir/sources/"
          && lcov -t "./build/tests/tests" -o coverage.info -c -d "./build/multy_matrix_tranposition_lib/CMakeFiles/th_m_transpose_lib.dir/sources/"
          && genhtml -o report coverage.info
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: codecov-report
          path: ./report